export const HudType = {
	TURN_BUTTON: 0,
  MAP: 1,
  PRODUCTION_PANEL: 2,
  PRODUCTION_UNIT: 3,
  PRODUCTION_BUILDING: 4,
  PRODUCTION_BUTTON: 5,
  TEAM_ICON: 6,
  SCIENCE_BUTTON: 7,
  PERK_BUTTON: 8
};