// All of game UI names
export enum HudType {
    // Game
    TURN_BUTTON = "TURN_BUTTON",
    MAP = "MAP",
    PRODUCTION_PANEL = "PRODUCTION_PANEL",
    PRODUCTION_UNIT = "PRODUCTION_UNIT",
    PRODUCTION_BUILDING = "PRODUCTION_BUILDING",
    PRODUCTION_BUTTON = "PRODUCTION_BUTTON",
    TEAM_ICON = "TEAM_ICON",
    SCIENCE_BUTTON = "SCIENCE_BUTTON",
    PERK_BUTTON = "PERK_BUTTON",

    // Menu
    MENU_SINGLE_BUTTON = "MENU_SINGLE_BUTTON",
    MENU_MULTI_BUTTON = "MENU_MULTI_BUTTON",
    MENU_MAP_EDITOR_BUTTON = "MENU_MAP_EDITOR_BUTTON",
    MENU_SETTING_BUTTON = "MENU_SETTING_BUTTON",
    MENU_EXIT_BUTTON = "MENU_EXIT_BUTTON",
    
    // Single player menu
    SINGLE_SETUP_GAME_BUTTON = "SINGLE_SETUP_GAME_BUTTON",
    LOAD_GAME_BUTTON = "LOAD_GAME_BUTTON",
    SINGLE_GO_BACK_BUTTON = "SINGLE_GO_BACK_BUTTON",

    // Single player set up game
    PLAYER_BOX = "PLAYER_BOX",
    PLAYER_TEAM_BUTTON = "PLAYER_TEAM_BUTTON",
    START_BUTTON = "START_BUTTON",
    SINGLE_SETUP_GO_BACK_BUTTON = "SINGLE_SETUP_GO_BACK_BUTTON",

    // Lobby
    LOBBY_SETUP_GAME_BUTTON = "LOBBY_SETUP_GAME_BUTTON",
    LOBBY_JOIN_GAME_BUTTON = "LOBBY_JOIN_GAME_BUTTON",
    LOBBY_GO_BACK_BUTTON = "LOBBY_GO_BACK_BUTTON",
    LOBBY_ROOM_HEAD = "LOBBY_ROOM_HEAD",
    LOBBY_ROOM_ROW = "LOBBY_ROOM_ROW",

    // Multi player set up game
    MULTI_NAME_INPUT = "MULTI_NAME_INPUT",
    MULTI_CONFIRM_GAME_BUTTON = "MULTI_CONFIRM_GAME_BUTTON",
    MULTI_SETUP_GO_BACK_BUTTON = "MULTI_SETUP_GO_BACK_BUTTON",

    // Multi player stage game
    MULTI_STAGE_PLAYER_BOX = "MULTI_STAGE_PLAYER_BOX",
    MULTI_STAGE_PLAYER_TEAM = "MULTI_STAGE_PLAYER_TEAM",
    MULTI_STAGE_READY_BUTTON = "MULTI_STAGE_READY_BUTTON",
    MULTI_STAGE_KICK_BUTTON = "MULTI_STAGE_KICK_BUTTON",
    MULTI_STAGE_GO_BACK_BUTTON = "MULTI_STAGE_GO_BACK_BUTTON",
    MULTI_STAGE_START_BUTTON = "MULTI_STAGE_START_BUTTON",
    MULTI_STAGE_LEAVE_BUTTON = "MULTI_STAGE_LEAVE_BUTTON",

    // Settings
    SETTING_GAME_BUTTON = "SETTING_GAME_BUTTON",
    SETTING_GRAPHICS_BUTTON = "SETTING_GRAPHICS_BUTTON",
    SETTING_AUDIO_BUTTON = "SETTING_AUDIO_BUTTON",

    // Map Editor
    MAP_EDITOR_GO_BACK_BUTTON = "MAP_EDITOR_GO_BACK_BUTTON",
    MAP_EDITOR_SETUP_BUTTON = "MAP_EDITOR_SETUP_BUTTON",
    MAP_EDITOR_SETUP_GO_BACK_BUTTON = "MAP_EDITOR_SETUP_GO_BACK_BUTTON"
}